import config from '@pixpilot/eslint-config-react';

const base = config({
  test: {
    relaxed: true,
  },
});

export default base.append(
  {
    linterOptions: {
      noInlineConfig: true,
    },
    rules: {
      'antfu/no-import-dist': 'off',
      'antfu/top-level-function': 'off',
      'arrow-body-style': 'off',
      'consistent-return': 'off',
      eqeqeq: 'off',
      'guard-for-in': 'off',
      'import/consistent-type-specifier-style': 'off',
      'import/no-duplicates': 'off',
      'import/first': 'off',
      'import/newline-after-import': 'off',
      'jsdoc/multiline-blocks': 'off',
      'jsx-a11y/alt-text': 'off',
      'jsx-a11y/click-events-have-key-events': 'off',
      'jsx-a11y/iframe-has-title': 'off',
      'jsx-a11y/label-has-associated-control': 'off',
      'jsx-a11y/no-static-element-interactions': 'off',
      'no-buffer-constructor': 'off',
      'no-await-in-loop': 'off',
      'no-bitwise': 'off',
      'no-continue': 'off',
      'no-else-return': 'off',
      'no-console': 'off',
      'no-implicit-coercion': 'off',
      'no-nested-ternary': 'off',
      'no-param-reassign': 'off',
      'no-promise-executor-return': 'off',
      'no-restricted-globals': 'off',
      'no-undef': 'off',
      'no-underscore-dangle': 'off',
      'no-undef-init': 'off',
      'no-unused-vars': 'off',
      'no-useless-concat': 'off',
      'no-useless-computed-key': 'off',
      'no-void': 'off',
      'node/no-deprecated-api': 'off',
      'node/global-require': 'off',
      'node/prefer-global/buffer': 'off',
      'node/prefer-global/process': 'off',
      'object-shorthand': 'off',
      'perfectionist/sort-exports': 'off',
      'perfectionist/sort-imports': 'off',
      'perfectionist/sort-named-imports': 'off',
      'prefer-destructuring': 'off',
      'prefer-named-capture-group': 'off',
      'prefer-const': 'off',
      'prefer-template': 'off',
      'react-hooks/rules-of-hooks': 'off',
      'react-dom/no-missing-button-type': 'off',
      'react-hooks-extra/no-unnecessary-use-prefix': 'off',
      'react-refresh/only-export-components': 'off',
      'react-web-api/no-leaked-timeout': 'off',
      'react/no-array-index-key': 'off',
      'react/no-leaked-conditional-rendering': 'off',
      'require-unicode-regexp': 'off',
      'style/jsx-curly-brace-presence': 'off',
      'style/spaced-comment': 'off',
      'test/prefer-hooks-in-order': 'off',
      'test/prefer-lowercase-title': 'off',
      'ts-no-autofix/promise-function-async': 'off',
      'ts/await-thenable': 'off',
      'ts/ban-ts-comment': 'off',
      'ts/consistent-type-definitions': 'off',
      'ts/consistent-type-imports': 'off',
      'ts/dot-notation': 'off',
      'ts/explicit-module-boundary-types': 'off',
      'ts/method-signature-style': 'off',
      'ts/no-require-imports': 'off',
      'ts/no-shadow': 'off',
      'ts/no-floating-promises': 'off',
      'ts/no-misused-promises': 'off',
      'ts/no-unnecessary-type-assertion': 'off',
      'ts/no-unsafe-argument': 'off',
      'ts/no-unsafe-assignment': 'off',
      'ts/no-unsafe-call': 'off',
      'ts/no-use-before-define': 'off',
      'ts/no-unsafe-member-access': 'off',
      'ts/no-unsafe-return': 'off',
      'ts/promise-function-async': 'off',
      'ts/return-await': 'off',
      'ts/restrict-template-expressions': 'off',
      'ts/strict-boolean-expressions': 'off',
      'ts/switch-exhaustiveness-check': 'off',
      'unused-imports/no-unused-imports': 'off',
      'unused-imports/no-unused-vars': 'off',
      'unicorn/no-new-buffer': 'off',
      'unicorn/prefer-includes': 'off',
      'unicorn/prefer-node-protocol': 'off',
      'yaml/plain-scalar': 'off',
      'regexp/no-super-linear-backtracking': 'off',
      'regexp/no-unused-capturing-group': 'off',
      'regexp/optimal-quantifier-concatenation': 'off',
    },
  },
  {
    ignores: ['README.md'],
  },
  {
    files: ['**/tsconfig.json'],
    rules: {
      'jsonc/sort-keys': 'off',
    },
  },
);
