export const ROUTE = {
  ADD_FAVOURITE_ACTION: '/actionSet/addFavouriteAction',
  CHANGE_SCREENSHOT_INDEX: '/screenshot/changeIndex',
  DELETE_ACTION_SET: '/actionSet/delete',
  DELETE_FAVOURITE_ACTION: '/actionSet/deleteFavouriteAction',
  DELETE_SCREENSHOT: '/screenshot/delete',
  DELETE_STORY_SCREENSHOT: '/screenshot/deleteStory',
  FIX_STORY_TITLE_CHANGE: '/story/fixTitleChange',
  GET_ACTIONS_DATA: '/screenshot/actionsData',
  GET_ACTION_SET: '/actionSet/get',
  GET_FAVOURITE_ACTIONS: '/actionSet/getFavouriteAction',
  GET_SCHEMA: '/getSchema',
  GET_STORY_SCREENSHOTS: '/screenshot/all',
  GET_THEME: '/getTheme',
  SAVE_ACTION_SET: '/actionSet/save',
  SAVE_SCREENSHOT: '/screenshot/save',
  TAKE_SCREENSHOT: '/screenshot/get',
  TEST_SCREENSHOT: '/screenshot/test',
  TEST_SCREENSHOTS: '/screenshot/testScreenshots',
  TEST_STORY_SCREENSHOT: '/screenshot/testStory',
  UPDATE_SCREENSHOT: '/screenshot/update',
};
