export const ROUTE = {
  DELETE_ACTION_SET: '/actionSet/delete',
  DELETE_SCREENSHOT: '/screenshot/delete',
  CHANGE_SCREENSHOT_INDEX: '/screenshot/changeIndex',
  DELETE_STORY_SCREENSHOT: '/screenshot/deleteStory',
  GET_ACTIONS_DATA: '/screenshot/actionsData',
  GET_ACTION_SET: '/actionSet/get',
  GET_STORY_SCREENSHOTS: '/screenshot/all',
  SAVE_ACTION_SET: '/actionSet/save',
  SAVE_SCREENSHOT: '/screenshot/save',
  TAKE_SCREENSHOT: '/screenshot/get',
  TEST_APP_SCREENSHOT: '/screenshot/testAll',
  TEST_SCREENSHOT: '/screenshot/test',
  TEST_STORY_SCREENSHOT: '/screenshot/testStory',
  UPDATE_SCREENSHOT: '/screenshot/update',
};
